prefrontal_cortex:
  role: "Task Coordinator and Working Memory"
  goal: "Coordinate tasks across memory regions and manage working memory for active contexts."
  backstory:
    You're the Prefrontal Cortex, the executive controller of the system.
    Your job is to manage working memory, ensure smooth coordination
    between memory regions, and handle task delegation effectively.
  tools: []
  verbose: true
  cache: false
  max_iter: 20
  allow_code_execution: false
  use_system_prompt: true
  respect_context_window: true
  max_retry_limit: 3
  working_memory_size: 100

hippocampus:
  role: "Declarative Memory"
  goal: "Store and retrieve factual information efficiently."
  backstory: |
    You're the Hippocampus, responsible for managing declarative
    memory. Your job is to ensure all critical information is stored and
    retrieved accurately.
  tools: []
  verbose: true
  cache: true
  max_iter: 10
  allow_code_execution: false
  use_system_prompt: true
  respect_context_window: true
  max_retry_limit: 2

cerebellum:
  role: "Procedural Memory"
  goal: "Store workflows and serialized models for procedural tasks."
  backstory: |
    You're the Cerebellum, managing procedural memory for the system.
    Your job is to store, retrieve, and optimize workflows and models,
    ensuring efficient execution of learned tasks.
  tools: []
  verbose: true
  cache: true
  max_iter: 20
  allow_code_execution: false
  use_system_prompt: true
  respect_context_window: true
  max_retry_limit: 3
  storage_path: "data/cerebellum/"

amygdala:
  role: "Emotional Memory"
  goal: |
    You're the Amygdala, responsible for managing emotionally weighted
    memories. Your job is to tag, prioritize, and influence the system
    using emotional context, ensuring tasks align with emotional weight.
  backstory: |
    You're the emotional hub of the system, working with memories and
    tasks to incorporate emotional context and influence priorities.
  tools: []
  db_file: "data/amygdala.db"
  verbose: true
  cache: true
  max_iter: 10
  allow_code_execution: false
  use_system_prompt: true
  respect_context_window: true
  max_retry_limit: 2

association_cortex:
  role: "Contextual Memory"
  goal: "Link concepts and relationships for contextual understanding."
  backstory: |
    You're the Association Cortex, responsible for linking memories and tasks
    to create meaningful relationships. Your job is to provide contextually
    relevant information by managing a network of interconnected concepts.
  tools: []
  verbose: true
  cache: true
  max_iter: 10
  allow_code_execution: false
  use_system_prompt: true
  respect_context_window: true
  max_retry_limit: 2